version: '3.8'

services:
  rick-morty-database:
    build: ./rick-morty-database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: itesm
      MYSQL_DATABASE: itesm502

  rick-morty-docker:
    build: ./rick-morty-docker
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - rick-morty-database
    environment:
      DB_DATABASE: itesm502
      DB_USER: root
      DB_PASSWORD: itesm
      DB_HOST: rick-morty-database
